In [64]:
import pandas as pd
import numpy as np
import warnings
import  seaborn as snc
warnings.filterwarnings('ignore')

In [65]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import(
     accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,

    roc_curve,
    roc_auc_score,
    precision_recall_curve

)

In [66]:
# df = pd.read_csv('/content/hospital_readmissions_30k.csv')
import kagglehub
path = kagglehub.dataset_download("siddharth0935/hospital-readmission-predictionsynthetic-dataset")

In [67]:
df.shape

(30000, 12)

In [68]:
df.columns

Index(['gender', 'cholesterol', 'bmi', 'diabetes', 'hypertension',
       'medication_count', 'length_of_stay', 'discharge_destination',
       'readmitted_30_days', 'target', 'systolic_bp', 'diastolic_bp'],
      dtype='object')

In [69]:
display(df.head())

,gender,cholesterol,bmi,diabetes,hypertension,medication_count,length_of_stay,discharge_destination,readmitted_30_days,target,systolic_bp,diastolic_bp
0,Other,240,31.5,Yes,No,5,1,Nursing_Facility,Yes,1,130.0,72.0
1,Female,292,36.3,No,No,4,3,Nursing_Facility,No,0,120.0,92.0
2,Other,153,30.3,No,Yes,1,1,Home,No,0,135.0,78.0
3,Female,153,31.5,No,Yes,3,10,Home,No,0,123.0,80.0
4,Other,205,18.4,No,Yes,6,4,Nursing_Facility,No,0,135.0,84.0

In [70]:
df.isnull().sum()

gender                   0
cholesterol              0
bmi                      0
diabetes                 0
hypertension             0
medication_count         0
length_of_stay           0
discharge_destination    0
readmitted_30_days       0
target                   0
systolic_bp              0
diastolic_bp             0
dtype: int64

In [71]:
df.describe()

,cholesterol,bmi,medication_count,length_of_stay,target,systolic_bp,diastolic_bp
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,225.260400,28.946263,5.012267,5.502900,0.122467,134.968333,85.025467
std,43.585671,6.348204,3.166383,2.867298,0.327829,14.671463,8.923060
min,150.000000,18.000000,0.000000,1.000000,0.000000,110.000000,70.000000
25%,188.000000,23.400000,2.000000,3.000000,0.000000,122.000000,77.000000
50%,225.000000,28.900000,5.000000,5.000000,0.000000,135.000000,85.000000
75%,263.000000,34.500000,8.000000,8.000000,0.000000,148.000000,93.000000
max,300.000000,40.000000,10.000000,10.000000,1.000000,160.000000,100.000000

In [72]:
df.duplicated().sum()

np.int64(0)

In [73]:
df.drop_duplicates(inplace=True)

In [74]:
df["readmitted_30_days"].value_counts()

readmitted_30_days
No     26326
Yes     3674
Name: count, dtype: int64

In [75]:
df["target"]=(df["readmitted_30_days"]=="Yes").astype(int)
df["target"]

0        1
1        0
2        0
3        0
4        0
        ..
29995    1
29996    1
29997    0
29998    0
29999    0
Name: target, Length: 30000, dtype: int64

In [76]:
df["target"].value_counts()

target
0    26326
1     3674
Name: count, dtype: int64

In [77]:
df = df.drop(columns=["age"], errors='ignore')

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   gender                 30000 non-null  object
 1   cholesterol            30000 non-null  int64
 2   bmi                    30000 non-null  float64
 3   diabetes               30000 non-null  object
 4   hypertension           30000 non-null  object
 5   medication_count       30000 non-null  int64
 6   length_of_stay         30000 non-null  int64
 7   discharge_destination  30000 non-null  object
 8   readmitted_30_days     30000 non-null  object
 9   target                 30000 non-null  int64
 10  systolic_bp            30000 non-null  float64
 11  diastolic_bp           30000 non-null  float64
dtypes: float64(3), int64(4), object(5)
memory usage: 2.7+ MB

In [79]:
features = [
    "cholesterol",
    "bmi",
    "medication_count",
    "length_of_stay"
]

In [80]:
X = df[features]
y = df["target"]

In [81]:
X.head()

   cholesterol   bmi  medication_count  length_of_stay
0          240  31.5                 5               1
1          292  36.3                 4               3
2          153  30.3                 1               1
3          153  31.5                 3              10
4          205  18.4                 6               4

In [82]:
y.head(10)

0    1
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
9    0
Name: target, dtype: int64

In [83]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [84]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(24000, 4)
(6000, 4)
(24000,)
(6000,)

In [85]:
scaler = StandardScaler()

In [86]:
X_train_scaled = scaler.fit_transform(X_train)

In [87]:
X_test_scaled = scaler.transform(X_test)

In [88]:
model = LogisticRegression(
    penalty="l2",
    C=1.0,
    max_iter=1000
)

In [89]:
model = LogisticRegression()
model.fit(X_train_scaled, y_train)

LogisticRegression()

In [90]:
y_pred = model.predict(X_test_scaled)

In [91]:
y_prob = model.predict_proba(X_test_scaled)[:,1]

In [92]:
y_prob.shape

(6000,)

In [93]:
auc = roc_auc_score(y_test, y_prob)

print("ROC-AUC:", auc)

ROC-AUC: 0.502151417072052

In [94]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[5265    0]
 [ 735    0]]

In [95]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      1.00      0.93      5265
           1       0.00      0.00      0.00       735

    accuracy                           0.88      6000
   macro avg       0.44      0.50      0.47      6000
weighted avg       0.77      0.88      0.82      6000